### ISSUE TITLE
Where is the link of NGSIM dataset??

### ISSUE THREAD

**Issue by Carrotsniper** [Petrichor625/BATraj-Behavior-aware-Model#2]

**Comment by Carrotsniper** [comment]
Sorry, I find the link of dataset.

**Comment by HHxxwshTTxs** [comment]
> 对不起，我找到了 dataset 的链接。

Could you please let me know if you have the preprocessing file for the NGSIM dataset. It has been removed from this project, if you can please send me a copy, thank you very much! Here is my email: WangShihao@emails.bjut.edu.cn
