### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by HHxxwshTTxs** [Petrichor625/BATraj-Behavior-aware-Model#9]
Dear Author, How should I run the predictive model for the RounD dataset?

**Comment by yachour1** [comment]
@HHxxwshTTxs hey did you have found any solutions for that ?

**Comment by HHxxwshTTxs** [comment]
> @HHxxwshTTxs hey did you have found any solutions for that ?

Unfortunately, not yet.

**Comment by yachour1** [comment]
@HHxxwshTTxs wassup what did you do ? did you succeed ?

**Comment by HHxxwshTTxs** [comment]
> 怎么了，你做了什么？你成功了吗？



> 怎么了，你做了什么？你成功了吗？

No, I can't get in touch with the author. I am considering using NGSIM for testing, do you have a preprocessor file for NGSIM? I noticed that this file has been removed from the project .

**Comment by yachour1** [comment]
Bro let's discuss out from there, here my linkedin https://www.linkedin.com/in/yassine-achour2710/
